---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
activity <- read.csv("activity.csv", header = TRUE)
activity <- transform(activity, date = as.Date(date))

## What is mean total number of steps taken per day?
stepsPerDay <- ddply(activity, ~date, summarise, steps = sum(steps))
p <- ggplot(stepsPerDay, aes(steps))
p <- p + geom_histogram(fill = "white", color = "black")
p <- p + ggtitle("Total number of steps per day")
p + xlab("Steps per day")

meanStepsPerDay <- mean(stepsPerDay$steps, na.rm = TRUE)
medianStepsPerDay <- median(stepsPerDay$steps, na.rm = TRUE)


## What is the average daily activity pattern?
avgStepsPerInterval <- ddply(activity, ~interval, summarise, mean = mean(steps, na.rm = T))
p <- ggplot(avgStepsPerInterval, aes(interval, mean)) + geom_line()
p <- p + ggtitle("The average daily activity pattern")
p + xlab("Interval") + ylab("Number of steps")

## 5-minute interval that contains the maximum number of steps on average across all the days in the dataset.
maxId <- which.max(avgStepsPerInterval$mean)
maxInterval <- avgStepsPerInterval$interval[maxId]

## Imputing missing values
numberRowNAs <- sum(apply(is.na(activity), 1, any))

## function to replace the NA's step by the mean of 5-minute interval averaged across all days.
na.replace <- function(act) {
    ddply(act, ~interval, function(dd) {
        steps <- dd$steps
        dd$steps[is.na(steps)] <- mean(steps, na.rm = TRUE)
        return(dd)
    })
}
## Create a new dataset that is equal to the original dataset but with the missing data filled in.

imputedActivity <- na.replace(activity)
## Find the total number of steps taken each day.

imputedStepsPerDay <- ddply(imputedActivity, ~date, summarise, steps = sum(steps))
## Make a histogram of the total number of steps taken each day.

p <- ggplot(imputedStepsPerDay, aes(steps))
p <- p + geom_histogram(fill = "white", color = "black")
p <- p + ggtitle("Total number of steps per day")
p + xlab("Steps per day")

## Calculate mean and median total number of steps taken per day.

imputedMeanStepsPerDay <- mean(imputedStepsPerDay$steps)
imputedMedianStepsPerDay <- median(imputedStepsPerDay$steps)

## Are there differences in activity patterns between weekdays and weekends?
## Create a new factor variable weekpart in the dataset with two levels “weekday” and “weekend”.

weekParts <- c("Weekday", "Weekend")
date2weekpart <- function(date) {
    day <- weekdays(date)
    part <- factor("Weekday", weekParts)
    if (day %in% c("Saturday", "Sunday")) 
        part <- factor("Weekend", weekParts)
    return(part)
}

imputedActivity$weekpart <- sapply(imputedActivity$date, date2weekpart)
## Make a panel plot containing a time series plot of the 5-minute interval and the average number of steps taken, averaged across all weekday days or weekend days.

avgSteps <- ddply(imputedActivity, .(interval, weekpart), summarise, mean = mean(steps))

p <- ggplot(avgSteps, aes(x = interval, y = mean))
p <- p + geom_line() + facet_grid(. ~ weekpart, )
p <- p + ggtitle("Activity patterns on weekends and weekdays")
p + xlab("Interval") + ylab("Number of steps")
